[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
hello_anchor = "GrpeGwCk8Rp44qx9gnwNXVEP9VU9fegmu7ZnWmkEo2eC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/wallet2.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
