[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_counter_dapp = "4akHsUQ9p4JNzRCyzCwkbKedMMkqy15C8hs4ouv5JTU6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/wallet2.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
